### ISSUE TITLE
symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by joel-simon** [david-hahn/FractureRB#1]
Hello, thanks for putting this repo up. I've managed to get most of the dependencies installed and issues worked out, but now getting the following compile issue after running make (on osx 10.10.1):

```
[ 44%] Linking CXX executable FractureBEM_vis
Undefined symbols for architecture x86_64:
  "openvdb::v2_2_0::initialize()", referenced from:
      FractureSim::VDBWrapper::VDBWrapper(double, double, bool) in libFractureLib.a(VDBWrapper.cpp.o)

      ...

  "openvdb::v2_2_0::GridBase::getName[abi:cxx11]() const", referenced from:
      FractureSim::VDBWrapper::getSegments(double, bool) const in libFractureLib.a(VDBWrapper_mesh.cpp.o)
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
make[2]: *** [FractureBEM_vis] Error 1
make[1]: *** [CMakeFiles/FractureBEM_vis.dir/all] Error 2
make: *** [all] Error 2
```

Any advice for solving this? My guess is there is as issue of the openVDB installation, althoguth not sure how I would check. I do have openvdb 2.2.0 installed. I'm also assuming osx binaries arn't available. Although that would be great.

The full output and other relevant files are attached
[debug_files.zip](https://github.com/david-hahn/FractureRB/files/288403/debug_files.zip)

Thanks again,
Joel

**Comment by david-hahn** [comment]
Hi Joel!

It looks like the linker can’t find OpenVDB. Can you check by building one of the basic examples from the OpenVDB webpage?

Depending on where/how the library is installed on your system you might need to adjust the following line in the CMakeLists.txt: “find_library(OpenVDBlib libOpenVDB)”.

Another thing you could try is to remove/adjust the OpenVDB version number in VDBWrapper.h where it says “namespace vdb = openvdb::v2_2_0;”. (I hardcoded the version for debugging originally, but I think it should also work without a version number – as far as I know all 2.x versions should have the same API, 3.x has some changes you’d have to track down yourself.)

As far as OSX is concerned, I’ve not worked with it myself, but I might be able to find someone in our group who knows how to work it. Can you let me know which version/compiler you’d be interested in, and I’ll see what I can do?

Best,

David

**Comment by joel-simon** [comment]
Hi David, 
Thanks for the fast reply. 

You were correct there is an issue with the VDB installation. I will work on that. I'm new to c++ compiling so Im still figuring things out. I'll close this issue for now and reopen it if I have further fractureRB install issues. 

Meanwhile, any binary for osx or ubuntu might save a lot of time and be very appreciated. Osx is 10.10.1 and ubuntu is 14.04. Let me know if any other info is needed. 

Cheers
Joel
