### ISSUE TITLE
Install issue: undefined references in linking FractureRB

### ISSUE THREAD

**Issue by joel-simon** [david-hahn/FractureRB#2]
Hello, 

Pardon the installation question but I'm unable to get past one of the final make linking steps.

Here is one of them:

> CMakeFiles/FractureRB.dir/src/FractureRB_fragments.cpp.o: In function `FractureSim::FractureRB::doCollisionUpdate()':
> FractureRB_fragments.cpp:(.text+0x17a4): undefined reference to`btRigidBody::setMassProps(double, btVector3 const&)'

Bullet is successfully installed and pasts tests, I have also tried with various releases of the bullet library. BULLET_COLLISION path is definitely correctly set to the libBulletCollision.so file and BULLET_INCLUDE is correct as well. I also tried using the .a files. FractureBEM and FractureBEM_vis successful link.

Before I started muckign around with the make file I was wondering if this was an issue you were aware of or knew how I might remedy it. I've already tried everything else I know of.  I am on ubuntu.

The full output is attached.
Thanks a lot!

[error_data.zip](https://github.com/david-hahn/FractureRB/files/303648/error_data.zip)

**Comment by david-hahn** [comment]
Hi,

It looks like not all of the required Bullet libraries are properly linked in.

As Bullet is quite modular, it is split across a bunch of libs; you’ll need all of the following: BulletDynamics, BulletCollision, LinearMath, BulletWorldImporter, and BulletFileLoader (the latter two are in “extras”).

Also please check that you are using version 2.83 because they changed the API quite a bit for v3.00.

Best,

David

**Comment by joel-simon** [comment]
Hi David, thank you for your response. 
I have confirmed all the Bullet libraries in the CMakeCache exist and are in the correct location. Also the 'extra' ones. A different error arrises when given the wrong path so it's finding all the .so files correctly.

e.x "BULLET_DYNAMICS:FILEPATH=/usr/local/lib/libBulletDynamics.so.2.83"

Is there anything else that might cause this error? I'm pretty stumped.

Thanks
Joel

**Comment by david-hahn** [comment]
Hi!

I think I figured out what’s going on: we’re working with double-precision Bullet libs by default. However that’s not the default configuration when building Bullet itself, so please make sure you either
- check the “USE_DOUBLE_PRECISION” option when building Bullet, or
- remove the line “add_definitions(-DBT_USE_DOUBLE_PRECISION)” in our CMakeLists.txt.

I should probably update the CMakeLists to add this as an option and match the defaults of Bullet.
Btw. my last few attempts at building on OS X have not gone well, so I'd recommend sticking to Linux or Windows.

Cheers,
David

**Comment by joel-simon** [comment]
Hi David,

Yes, that fixed the issue! Everything works fine now. 

Thanks again for your help, it may have taken me a while to realize to look at that,
Joel
